### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by centurionj** [centurionj/education_platform#1]
- [ ] разграничение доступа к моделям в админке (препод частичный доступ)
- [ ] механизм построения тестов в админке
- [ ] вывод тестов на фронт
- [ ] обработка результатов
- [ ] интеграция компилятора

- [ ] формирования отчета с результатами тестирования
- [ ] отправка на почту преподу по кнопке

- [ ] подсчет кол-ва тестов в курсе для вывода на фронте
- [ ] подсчет % прохождения курса по тестам и/или лекциям
